### ISSUE TITLE
Fails to create output directory of disc title too long

### ISSUE THREAD

**Issue by Fregf** [JoeLametta/whipper#207] opened 2017-12-03 16:21 UTC
When the disc title is too long, the whipper call to mkdir fails. whipper should cut off too long titles.

```
Checking device /dev/sr0
CDDB disc id: 8d0bef0a
MusicBrainz disc id o7JlGFtrV041Te1upvH_SgIRWCA-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+10+229308+183+40383+58908+88758+121758+142908+166683+190683+214158+221733&tracks=10&id=o7JlGFtrV041Te1upvH_SgIRWCA-
Disc duration: 00:50:55.000, 10 audio tracks

Matching releases:

Artist  : Игорь Фёдорович Стравинский; Pierre Boulez
Title   : Boulez Conducts Stravinsky (Disc 5 of 6): Ebony Concerto / 3 Pieces for Clarinet solo / Concertino for String Quartet / 8 Instrumental Miniatures / Concerto “Dumbarton Oaks” / Elegy for Viola solo / Epitaphium / Double Canon for String Quartet
Duration: 00:50:55.000
URL     : https://musicbrainz.org/release/423f636d-742d-47b0-9ba2-51515a6fdfd2
Release : 423f636d-742d-47b0-9ba2-51515a6fdfd2
Type    : Compilation
Barcode : 028947787303
Cat no  : 6CD 477 8730 GB6

Creating output directory ./compilation/Игорь Фёдорович Стравинский; Pierre Boulez - Boulez Conducts Stravinsky (Disc 5 of 6) - Ebony Concerto - 3 Pieces for Clarinet solo - Concertino for String Quartet - 8 Instrumental Miniatures - Concerto _Dumbarton Oaks_ - Elegy for Viola solo - Epitaphium - Double Canon for String Quartet
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.5.1', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.5.1-py2.7.egg/whipper/command/main.py", line 32, in main
    ret = cmd.do()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.5.1-py2.7.egg/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.5.1-py2.7.egg/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.5.1-py2.7.egg/whipper/command/cd.py", line 213, in do
    self.doCommand()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.5.1-py2.7.egg/whipper/command/cd.py", line 377, in doCommand
    os.makedirs(dirname)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: './compilation/\xd0\x98\xd0\xb3\xd0\xbe\xd1\x80\xd1\x8c \xd0\xa4\xd1\x91\xd0\xb4\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb8\xd1\x87 \xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd0\xb2\xd0\xb8\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9; Pierre Boulez - Boulez Conducts Stravinsky (Disc 5 of 6) - Ebony Concerto - 3 Pieces for Clarinet solo - Concertino for String Quartet - 8 Instrumental Miniatures - Concerto _Dumbarton Oaks_ - Elegy for Viola solo - Epitaphium - Double Canon for String Quartet'
```

**Comment by gorgobacka** [comment] 2017-12-03 21:17
Thanks. But there is already a similar issue: https://github.com/JoeLametta/whipper/issues/197

**Comment by JoeLametta** [comment] 2018-01-04 20:16
Thanks for the report.
As already stated by gorgobacka this is a duplicate of issue #197.
I'm closing this issue, please continue discussing it in the other ticket.

**Closed by JoeLametta** 2018-01-04 20:16 UTC
Labels: duplicate
