### ISSUE TITLE
Remove the link to the thomasvs/morituri repo

### ISSUE THREAD

**Issue by thomas-mc-work** [JoeLametta/whipper#236] opened 2018-02-23 10:23 UTC
On Github this repository is still marked as:
> forked from thomasvs/morituri

I suggest to remove this link because there is no reason to keep it. The changes will probably never get merged back upstream. And the link prevents to search the sources on Github.

(I only refer to the project settings, not to the information in the README. I think it should be kept there as a credit)

**Comment by JoeLametta** [comment] 2018-02-23 11:35
Hi, this is a duplicate of #79. Please discuss the issue there.

Thanks,
Joe

**Closed by JoeLametta** 2018-02-23 11:35 UTC
Labels: duplicate
